# Generated by Django 3.2.8 on 2021-11-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_schedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day',
        ),
    ]
